name: 'Generate Release Notes from Milestone'
description: 'Generates release notes for a specified milestone.'
author: 'Jeff Patton'

branding:
  icon: 'activity'
  color: 'blue'

inputs:
  milestone_number:
    description: 'The milestone number for which to generate release notes.'
    required: true
    type: number

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create ReleaseNotes
      env:
        MilestoneNumber: ${{ inputs.milestone_number }}
      run: |
        & $env:GITHUB_ACTION_PATH\\issue2releasenotes.ps1 -MilestoneNumber $MilestoneNumber
      shell: pwsh

    - name: Upload Release Notes
      uses: actions/upload-artifact@v2
      with:
        name: release-notes
        path: RELEASE.md
