name: 'Generate Release Notes from Milestone'
description: 'Generates release notes for a specified milestone.'
author: 'Jeff Patton'

branding:
  icon: 'activity'
  color: 'blue'

inputs:
  milestone_number:
    description: 'The milestone number for which to generate release notes.'
    required: true
    type: string
  verbose:
    description: "A value of verbose will output additional information"
    required: false
    type: string
    default: 'None'
  github_token:
    description: 'GitHub token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create ReleaseNotes
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        VERBOSE: ${{ inputs.verbose }}
      run: |
        & $env:GITHUB_ACTION_PATH\\issue2releasenotes.ps1 -MilestoneNumber ${{ inputs.milestone_number }}
      shell: pwsh

    - name: Upload Release Notes
      uses: actions/upload-artifact@v2
      with:
        name: release-notes
        path: RELEASE.md

    - name: Download Release Notes
      uses: actions/download-artifact@v2
      with:
        name: release-notes

    - name: Set up Git User
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
      shell: pwsh

    - name: Commit and Push Release Notes
      run: |
        git add RELEASE.md
        git commit -m "Add release notes for milestone ${{ inputs.milestone_number }}"
        git push
      shell: pwsh
