name: Generate Release Notes

on:
  workflow_call:
    inputs:
      milestone_number:
        required: true
        type: number

jobs:
  create_releasenotes:
    runs-on: windows-latest
    name: Create Project Release Notes
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: List Files
        run: ls

      - name: Create Releasenotes
        env:
          MilestoneNumber: ${{ inputs.milestone_number }}
        run: |
          pwsh -File issue2releasenotes.ps1 -MilestoneNumber $MilestoneNumber
        shell: pwsh

      - name: Upload Release Notes
        uses: actions/upload-artifact@v2
        with:
          name: release-notes
          path: RELEASE.md
